name = "JuliaRAG"
uuid = "7fb97b74-f14f-400d-bab7-a2fb2c984d97"
authors = ["Connor Smith"]
version = "1.0.7-DEV"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
Distances = "0.10"
PythonCall = "0.9"
NearestNeighbors = "0.4"
CondaPkg = "0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
